version: "3.4"

services:
    storage:
        build:
            context: ./storage/
            dockerfile: Dockerfile
        container_name: storage
        restart: always
        environment:
            MYSQL_HOST: "storage"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "webarelyremember"
            MYSQL_ROOT_PASSWORD: "webarelyremember"
        ports:
            - "3306:3306"

    order-manager:
        build:
            context: ./application/
            dockerfile: Dockerfile
        container_name: order-manager
        restart: always
        depends_on:
            - storage
        links:
            - storage
        environment:
            MYSQL_HOST: "storage"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "webarelyremember"
            SERVER_PORT: "7777"
            WAIT_HOSTS: storage:3306
            WAIT_HOSTS_TIMEOUT: 300
        ports:
            - "7777:7777"
        expose:
            - "7777"