CREATE DATABASE IF NOT EXISTS `storage`;

USE `storage`;

CREATE TABLE IF NOT EXISTS `order` (
	`id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`contact` VARCHAR(255) NOT NULL,
	`pid` VARCHAR(64) NOT NULL,
	`shipping` DECIMAL(15, 2) UNSIGNED NOT NULL,
	CONSTRAINT `pk_order` PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `item` (
	`id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
	`order` INT(12) UNSIGNED NOT NULL,
	`sku` VARCHAR(32) NOT NULL,
	`price` DECIMAL(15, 2) UNSIGNED NOT NULL,
	`amount` INT(9) UNSIGNED DEFAULT 1,
	`description` VARCHAR(1024) NOT NULL,
	CONSTRAINT `uk_item` UNIQUE (`id`),
	CONSTRAINT `pk_item` PRIMARY KEY (`order`, `sku`),
	CONSTRAINT `fk_item_order` FOREIGN KEY (`order`) REFERENCES `order`(`id`)
);